### Playlists
Created x01
{
  "id": "ba9a88be-e85b-4eaf-9085-0c02d18c9d26",
  "name": "Nadia Playlist x01"
}

Created x02
{
  "id": "91a67b0c-b7a1-4486-a3ea-070290647458",
  "name": "Nadia Playlist x02"
}

Created x03
{
  "id": "55f0eec2-62f8-4ae7-b789-8cb242a5b8d9",
  "name": "Nadia Playlist x03"
}

### Musics
Playlist x01
{
  "quantity": 2,
  "musics": [
    {
      "id": "17369a99-c7c3-4ec1-954a-523c502ccb36",
      "name": "Awesome Music 11",
      "artist": "Awesome4",
      "url": "http://spoti4.future4.com.br/11.mp3"
    },
    {
      "id": "2b1cf820-de4a-477d-adda-e0bbaeb8ebc8",
      "name": "Awesome Music 12",
      "artist": "Awesome4",
      "url": "http://spoti4.future4.com.br/12.mp3"
    }
  ]
}
New Musics in Favorite Playlist
{
  "id": "f5151269-bc32-4c60-899a-99f57c87f20e",
  "name": "Awesome Music 13",
  "artist": "Awesome4",
  "url": "http://spoti4.future4.com.br/13.mp3"
},
{
  "id": "34ea0d8a-7cef-408b-9f71-9dce0ad1f586",
  "name": "Awesome Music 14",
  "artist": "Awesome4",
  "url": "http://spoti4.future4.com.br/14.mp3"
}

Playlist x02
{
  "quantity": 2,
  "musics": [
    {
      "id": "ab5ea427-ab90-481a-9be5-e64517f9d113",
      "name": "Awesome Music 22",
      "artist": "Awesome4",
      "url": "http://spoti4.future4.com.br/22.mp3"
    },
    {
      "id": "252715f1-0330-4a27-9bfb-31c215340f52",
      "name": "Awesome Music 21",
      "artist": "Awesome4",
      "url": "http://spoti4.future4.com.br/21.mp3"
    }
  ]
}
New Music in Disliked Playlist (Will be Deleted)
{
  "id": "b4b20ce9-0be6-4946-850a-dd5763e1d038",
  "name": "Awesome Music 23",
  "artist": "Awesome4",
  "url": "http://spoti4.future4.com.br/22.mp3"
}
New Musics to Playlist
{
  "id": "4a463527-0f1c-4227-9241-2a5fc0b1460e",
  "name": "Awesome Music 24",
  "artist": "Awesome4",
  "url": "http://spoti4.future4.com.br/24.mp3"
},
{
  "id": "7e4023db-45e3-44f2-aba3-f2ca1b39bce0",
  "name": "Awesome Music 25",
  "artist": "Awesome4",
  "url": "http://spoti4.future4.com.br/25.mp3"
}

Playlist x03
{
  "quantity": 2,
  "musics": [
    {
      "id": "8b0b5aa9-933f-45ad-9ce9-29a7fd25fb60",
      "name": "Awesome Music 31",
      "artist": "Awesome4",
      "url": "http://spoti4.future4.com.br/31.mp3"
    },
    {
      "id": "220f0d0d-eef7-4778-bdad-df8c95bdc73f",
      "name": "Awesome Music 32",
      "artist": "Awesome4",
      "url": "http://spoti4.future4.com.br/32.mp3"
    }
  ]
}